apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-client.fullname" . }}-env-config
  labels:
    {{- include "app-client.labels" . | nindent 4 }}
data:
{{ toYaml $.Values.configMap | indent 2 }}
