apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : app-api
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: eks-prod
  source:
    path   : "HelmCharts/app-api"
    repoURL: "git@github.com:eliasaf-abargel/multi-project-argocd.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-prod.yaml
      parameters:
      - name: "image.tag"
        value: "app-api-latest"

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
