apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : work-hours-api
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: eks-prod
  source:
    path   : "HelmCharts/work-hours-api"
    repoURL: "git@github.com:eliasaf-abargel/multi-project-argocd.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-prod.yaml
      parameters:
      - name: "image.tag"
        value: "work-hours-api-latest"

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
