apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: argocd
  source:
    repoURL       : "git@github.com:eliasaf-abargel/multi-project-argocd.git"
    path          : "eks-prod/applications"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Validate=true
      - PruneLast=true
    retryStrategy:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
