apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "splunk-otel-collector.fullname" . }}
  labels:
    {{- include "splunk-otel-collector.labels" . | nindent 4 }}
  annotations:
    # Record deployment cause for rollback purposes
    kubernetes.io/change-cause: "Version {{ .Chart.AppVersion }} deployed at {{ now | date "2006-01-02T15:04:05Z07:00" }}"
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "splunk-otel-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "splunk-otel-collector.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "splunk-otel-collector.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      # Give time for graceful shutdown
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SPLUNK_HEC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "splunk-otel-collector.fullname" . }}-secrets
                  key: splunk-hec-token
            - name: SPLUNK_HEC_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ include "splunk-otel-collector.fullname" . }}-secrets
                  key: splunk-hec-endpoint
            - name: SPLUNK_INDEX
              valueFrom:
                secretKeyRef:
                  name: {{ include "splunk-otel-collector.fullname" . }}-secrets
                  key: splunk-index
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: metrics
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config-volume
              mountPath: /etc/otel/config.yaml
              subPath: collector-config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: config-volume
          configMap:
            name: {{ include "splunk-otel-collector.fullname" . }}-config
            items:
              - key: collector-config.yaml
                path: collector-config.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
