# This looks good overall, just need to ensure index consistency
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splunk-otel-collector.fullname" . }}-secrets
  labels:
    {{- include "splunk-otel-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  splunk-hec-token: {{ required "A valid .Values.splunk.token entry is required!" .Values.splunk.token | quote }}
  splunk-hec-endpoint: {{ .Values.splunk.endpoint | quote }}
  splunk-index: {{ .Values.splunk.index | default "k8-Dev" | quote }}
