apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-otel-collector.fullname" . }}
  labels:
    {{- include "splunk-otel-collector.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: 4318
      targetPort: otlp-http
      protocol: TCP
      name: otlp-http
    - port: 8888
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "splunk-otel-collector.selectorLabels" . | nindent 4 }}
