{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "splunk-otel-collector.serviceAccountName" . }}
  labels:
    {{- include "splunk-otel-collector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}

---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "splunk-otel-collector.fullname" . }}
  labels:
    {{- include "splunk-otel-collector.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - namespaces
      - services
      - pods
      - endpoints
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - replicasets
      - deployments
      - statefulsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources:
      - replicasets
      - deployments
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - nodes/stats
      - configmaps
      - events
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - pods/log
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "splunk-otel-collector.fullname" . }}
  labels:
    {{- include "splunk-otel-collector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "splunk-otel-collector.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "splunk-otel-collector.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
